# Configuration Read the Docs
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
  - pdf
  - htmlzip
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    # Supprimé: method: pip / path: . car pas de setup.py

# Supprimé: submodules car probablement pas nécessaire
# submodules:
#   include: all
#   recursive: true
